apiVersion: v1
kind: Service
metadata:
  labels:
    app: anm
  name: anmsvc
  namespace: axway
spec:
  type: NodePort
  selector:
    app: anm
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30090

