apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    
    type: front-endtwo
spec:
  replicas: 3
  selector:
    app: myapp
    type: front-end
  template:
    metadata:
      name: my-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          
