apiVersion: v1
kind: ReplicationController
metadata:
  - name: my-rc
    labels:
      app: myapp
      type: fron-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: fron-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3