apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc1
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  selector:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: mnginx-container
          image: nginx
          
