apiVersion: v1
kind: ReplicationSet
metadata:
  name: my-rs
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  teplate:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - image:  nginx-container
          name: nginx
  selector:
    matchLabels:
      type: front-end
        