apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs1
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: my-nginx
          image: nginx
  selector:
    matachLables:
      type: front-end