apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      reauiredDuringSchedulingIngnoredDuringExecution:
        nodeSelectorTerms:
          - matechExpression:
            - key: disktype
              operator: In
              values:
               - ssd
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
